# language setting
language: node_js

# version numbers, testing against two versions of node
node_js:
    - 0.10.25
    - 0.11
    
# npm install runs by default but shown here for illustrative purposes
before_install:
    - npm install docco
    - npm install coffee-script
# Running npm test to run your test cases
script:
    - npm test
